#!/bin/bash
if [[ $# -eq 0 ]]; then
  echo "Use: $0 \"string\"" >&2
  exit 1
fi

len=${#1}
printf "+"

for (( i=0; i < len + 2; i++ )); do
  printf "-"
done

printf "+\n"

printf "| %s |\n" "$1"

printf "+"

for (( i=0; i < len + 2; i++ )); do
  printf "-"
done

printf "+\n"