#!/bin/bash

if [[ $# -ne 1 ]]; then
  echo "Use: $0 file" >&2
  exit 1
fi

if [[ ! -f "$1" ]]; then
  echo "$0: $1: not a regular file" >&2
  exit 1
fi

if [[ ! "$1" =~ \.(c|js|py)$ ]]; then
  echo "$0: $1: is not a js/c/py file" >&2
  exit 1
fi

case "$1" in
  *.py)      re='^[[:space:]]*#' ;;
  *.c|*.js)  re='^[[:space:]]*(//|/\*)' ;;
esac

first_line=$(head -n 1 "$1")

if [[ "first_line" =~ $re && "$first_line" != '#!'* ]];then
  echo "$1: комментарий есть"
else
  echo "$1: комментария нет"
fi